-- Migration 00017: Seed expanded license & registration requirements
-- Personalized per MSME category (micro/small/medium)

-- Add more compliance requirements with applicability rules per MSME size
INSERT INTO public.compliance_requirements (code, title, title_hi, description, description_hi, category, act_name, jurisdiction_country, jurisdiction_state, applicability_rules, frequency, due_day_offset, penalty_details, penalty_details_hi)
VALUES
  -- === UNIVERSAL (All MSMEs) ===
  ('UDYAM_REGISTRATION', 'Udyam Registration Certificate', 'उद्यम पंजीकरण प्रमाणपत्र', 'Mandatory MSME registration under Udyam portal for all micro, small and medium enterprises', 'सभी सूक्ष्म, लघु एवं मध्यम उद्यमों के लिए उद्यम पोर्टल पर अनिवार्य MSME पंजीकरण', 'corporate_and_msme', 'MSMED Act, 2006', 'IN', NULL, '{"turnover_bands": ["micro","small","medium"], "employee_bands": ["1-9","10-19","20-49","50-249","250+"]}', 'one_time', 0, 'Operations without Udyam registration may disqualify from government scheme benefits', 'उद्यम पंजीकरण के बिना संचालन से सरकारी योजना लाभ से वंचित हो सकते हैं'),

  ('GST_REGISTRATION', 'GST Registration', 'GST पंजीकरण', 'Goods and Services Tax registration mandatory for businesses with turnover above threshold', 'सीमा से अधिक कारोबार वाले व्यवसायों के लिए वस्तु एवं सेवा कर पंजीकरण अनिवार्य', 'taxation', 'CGST Act, 2017', 'IN', NULL, '{"turnover_bands": ["micro","small","medium"]}', 'one_time', 0, 'Penalty up to ₹25,000 or 10% of tax due for non-registration', 'गैर-पंजीकरण के लिए ₹25,000 या देय कर का 10% तक जुर्माना'),

  ('PAN_REGISTRATION', 'PAN Card (Business)', 'PAN कार्ड (व्यवसाय)', 'Permanent Account Number mandatory for all business entities for tax compliance', 'कर अनुपालन के लिए सभी व्यावसायिक संस्थाओं के लिए स्थायी खाता संख्या अनिवार्य', 'taxation', 'Income Tax Act, 1961', 'IN', NULL, '{"turnover_bands": ["micro","small","medium"]}', 'one_time', 0, 'Penalty of ₹10,000 under Section 272B for not obtaining PAN', 'PAN न प्राप्त करने पर धारा 272B के तहत ₹10,000 का जुर्माना'),

  ('TAN_REGISTRATION', 'TAN Registration', 'TAN पंजीकरण', 'Tax Deduction Account Number required if business deducts TDS on payments', 'यदि व्यवसाय भुगतान पर TDS काटता है तो कर कटौती खाता संख्या आवश्यक', 'taxation', 'Income Tax Act, 1961', 'IN', NULL, '{"turnover_bands": ["micro","small","medium"], "employee_bands": ["10-19","20-49","50-249","250+"]}', 'one_time', 0, 'Penalty of ₹10,000 for non-application of TAN', 'TAN का आवेदन न करने पर ₹10,000 का जुर्माना'),

  ('TRADE_LICENSE_UP', 'Trade License (Uttar Pradesh)', 'व्यापार लाइसेंस (उत्तर प्रदेश)', 'Municipal trade license required for operating business within UP municipal limits', 'UP नगरपालिका सीमा के भीतर व्यवसाय संचालित करने के लिए नगरपालिका व्यापार लाइसेंस आवश्यक', 'corporate_and_msme', 'UP Nagar Nigam Act', 'IN', 'UP', '{"turnover_bands": ["micro","small","medium"]}', 'annual', 31, 'Late fee + penalty for operating without valid trade license', 'वैध व्यापार लाइसेंस के बिना संचालन के लिए विलंब शुल्क + जुर्माना'),

  ('MSME_DI_REGISTRATION', 'MSME-DI Registration', 'MSME-DI पंजीकरण', 'Registration with District Industries Centre for availing state government schemes', 'राज्य सरकार की योजनाओं का लाभ उठाने के लिए जिला उद्योग केंद्र में पंजीकरण', 'corporate_and_msme', 'MSMED Act, 2006', 'IN', 'UP', '{"turnover_bands": ["micro","small","medium"]}', 'one_time', 0, 'May lose eligibility for UP state industrial incentives', 'UP राज्य औद्योगिक प्रोत्साहन पात्रता खो सकते हैं'),

  -- === SMALL & MEDIUM (10+ employees or higher turnover) ===
  ('EPF_REGISTRATION', 'EPF Registration', 'EPF पंजीकरण', 'Employees Provident Fund registration mandatory for establishments with 20+ employees', '20+ कर्मचारियों वाले प्रतिष्ठानों के लिए कर्मचारी भविष्य निधि पंजीकरण अनिवार्य', 'labor_and_employment', 'EPF Act, 1952', 'IN', NULL, '{"turnover_bands": ["small","medium"], "employee_bands": ["20-49","50-249","250+"]}', 'one_time', 0, 'Penalty up to ₹1 lakh and/or imprisonment for non-registration', 'गैर-पंजीकरण के लिए ₹1 लाख तक जुर्माना और/या कारावास'),

  ('ESI_REGISTRATION', 'ESI Registration', 'ESI पंजीकरण', 'Employees State Insurance registration for establishments with 10+ employees', '10+ कर्मचारियों वाले प्रतिष्ठानों के लिए कर्मचारी राज्य बीमा पंजीकरण', 'labor_and_employment', 'ESI Act, 1948', 'IN', NULL, '{"turnover_bands": ["small","medium"], "employee_bands": ["10-19","20-49","50-249","250+"]}', 'one_time', 0, 'Penalty under Section 85 of ESI Act for non-compliance', 'ESI अधिनियम की धारा 85 के तहत गैर-अनुपालन के लिए जुर्माना'),

  ('PROFESSIONAL_TAX_UP', 'Professional Tax Registration (UP)', 'व्यावसायिक कर पंजीकरण (UP)', 'Professional tax registration required for employers in Uttar Pradesh', 'उत्तर प्रदेश में नियोक्ताओं के लिए व्यावसायिक कर पंजीकरण आवश्यक', 'taxation', 'UP Tax on Professions Act', 'IN', 'UP', '{"turnover_bands": ["small","medium"], "employee_bands": ["10-19","20-49","50-249","250+"]}', 'annual', 15, 'Penalty for late filing of professional tax returns', 'व्यावसायिक कर रिटर्न की विलंब फाइलिंग के लिए जुर्माना'),

  -- === MEDIUM ENTERPRISES ===
  ('COMPANY_ANNUAL_RETURN', 'Company Annual Return (MCA)', 'कंपनी वार्षिक रिटर्न (MCA)', 'Annual return filing with Ministry of Corporate Affairs for registered companies', 'पंजीकृत कंपनियों के लिए कॉर्पोरेट मामलों के मंत्रालय में वार्षिक रिटर्न दाखिल', 'corporate_and_msme', 'Companies Act, 2013', 'IN', NULL, '{"turnover_bands": ["medium"], "employee_bands": ["50-249","250+"]}', 'annual', 60, 'Additional fee of ₹100/day for late filing, up to 12x normal fees', 'विलंब फाइलिंग के लिए ₹100/दिन अतिरिक्त शुल्क, सामान्य शुल्क का 12 गुना तक'),

  ('STATUTORY_AUDIT', 'Statutory Audit', 'सांविधिक ऑडिट', 'Mandatory annual audit by chartered accountant for companies and businesses above threshold', 'सीमा से ऊपर की कंपनियों और व्यवसायों के लिए चार्टर्ड अकाउंटेंट द्वारा अनिवार्य वार्षिक ऑडिट', 'corporate_and_msme', 'Companies Act, 2013', 'IN', NULL, '{"turnover_bands": ["medium"], "employee_bands": ["50-249","250+"]}', 'annual', 90, 'Fine of ₹25,000 to ₹5,00,000 for non-compliance', 'गैर-अनुपालन के लिए ₹25,000 से ₹5,00,000 तक जुर्माना'),

  ('IMPORT_EXPORT_CODE', 'Import Export Code (IEC)', 'आयात निर्यात कोड (IEC)', 'IEC registration with DGFT required for businesses involved in import/export', 'आयात/निर्यात में लगे व्यवसायों के लिए DGFT के साथ IEC पंजीकरण आवश्यक', 'corporate_and_msme', 'Foreign Trade Policy', 'IN', NULL, '{"turnover_bands": ["small","medium"], "sectors": ["Textiles & Apparel","Leather & Footwear","Handicrafts & Carpet Manufacturing","Chemicals & Pharmaceuticals"]}', 'one_time', 0, 'Cannot undertake import/export activities without valid IEC', 'वैध IEC के बिना आयात/निर्यात गतिविधियां नहीं कर सकते'),

  -- === INDUSTRY SPECIFIC ===
  ('FIRE_NOC', 'Fire Safety NOC', 'अग्नि सुरक्षा NOC', 'Fire safety no-objection certificate required for manufacturing and commercial establishments', 'विनिर्माण और वाणिज्यिक प्रतिष्ठानों के लिए अग्नि सुरक्षा अनापत्ति प्रमाणपत्र आवश्यक', 'industry_specific', 'Fire Services Act', 'IN', 'UP', '{"turnover_bands": ["small","medium"], "sectors": ["Food Processing & Confectionery","Chemicals & Pharmaceuticals","Textiles & Apparel","Automotive & Engineering Components"]}', 'annual', 30, 'Closure order possible, fine up to ₹50,000', 'बंद करने का आदेश संभव, ₹50,000 तक जुर्माना'),

  ('POLLUTION_CONSENT', 'Pollution Control Board Consent (CTE/CTO)', 'प्रदूषण नियंत्रण बोर्ड सहमति (CTE/CTO)', 'Consent to Establish (CTE) and Consent to Operate (CTO) from UP Pollution Control Board', 'UP प्रदूषण नियंत्रण बोर्ड से स्थापना की सहमति (CTE) और संचालन की सहमति (CTO)', 'environmental', 'Water Act 1974 / Air Act 1981', 'IN', 'UP', '{"turnover_bands": ["small","medium"], "sectors": ["Food Processing & Confectionery","Chemicals & Pharmaceuticals","Leather & Footwear","Textiles & Apparel"]}', 'annual', 60, 'Imprisonment up to 6 years and/or fine up to ₹1 lakh per day', '6 वर्ष तक कारावास और/या ₹1 लाख प्रतिदिन तक जुर्माना'),

  ('BIS_CERTIFICATION', 'BIS Certification', 'BIS प्रमाणन', 'Bureau of Indian Standards certification required for specific product categories', 'विशिष्ट उत्पाद श्रेणियों के लिए भारतीय मानक ब्यूरो प्रमाणन आवश्यक', 'industry_specific', 'BIS Act, 2016', 'IN', NULL, '{"turnover_bands": ["small","medium"], "sectors": ["Food Processing & Confectionery","Chemicals & Pharmaceuticals","Automotive & Engineering Components"]}', 'annual', 30, 'Fine up to ₹10 lakh and/or imprisonment for selling without BIS mark', 'BIS चिह्न के बिना बिक्री के लिए ₹10 लाख तक जुर्माना और/या कारावास'),

  ('LABOUR_LICENSE_UP', 'Contract Labour License (UP)', 'ठेका श्रम लाइसेंस (UP)', 'License required under Contract Labour Act when employing 20+ contract workers in UP', 'UP में 20+ अनुबंध श्रमिकों को रोजगार देते समय अनुबंध श्रम अधिनियम के तहत लाइसेंस आवश्यक', 'labor_and_employment', 'Contract Labour (R&A) Act, 1970', 'IN', 'UP', '{"turnover_bands": ["small","medium"], "employee_bands": ["20-49","50-249","250+"]}', 'annual', 30, 'Fine up to ₹1,000 and/or imprisonment for non-compliance', 'गैर-अनुपालन के लिए ₹1,000 तक जुर्माना और/या कारावास')

ON CONFLICT (code) DO NOTHING;
